/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restclient;

/**
 *
 * @author yann
 */
//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//Any modifications to this file will be lost upon recompilation of the source schema.
//Generated on: 2014.01.25 at 05:56:27 PM CET
//


import javax.xml.bind.annotation.*;

import resource.*;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
public class Stage extends Resource {

 @XmlSchemaType(name = "ID")
 protected String ID;
 @XmlSchemaType(name = "SIRET")
 protected String SIRET;
 @XmlSchemaType(name = "TITRESUJET")
 protected String TITRESUJET;
 @XmlSchemaType(name = "REFERENCE")
 protected String REFERENCE;
 @XmlSchemaType(name = "DESCRIPTIONSUJET")
 protected String DESCRIPTIONSUJET;
 @XmlSchemaType(name = "SPECIALITE")
 protected String SPECIALITE;
 @XmlSchemaType(name = "REMUNERATION")
 protected String REMUNERATION;
 @XmlSchemaType(name = "ADRESSE")
 protected String ADRESSE;
 @XmlElement(name = "contactname")
 protected String CONTACTNAME;
 @XmlSchemaType(name = "CONTACTTEL")
 protected String CONTACTTEL;
 @XmlSchemaType(name = "CONTACTWEB")
 protected String CONTACTWEB;
 @XmlSchemaType(name = "TYPECONTRAT")
 protected String TYPECONTRAT;
 @XmlSchemaType(name = "DUREE")
 protected String DUREE;
 @XmlSchemaType(name = "NIVEAUETUDE")
 protected String NIVEAUETUDE;
 /**
  * Application Constructor
  */
 public Stage() {
     super();
 }

 /**
  * Application Constructor
  * @param appId - The id of the application
  */
 public Stage(String Id) {
     super();
     this.ID = Id;
 }
 
 public Stage(String ADRESSE,String CONTACTNAME,String CONTACTTEL,String DESCRIPTIONSUJET, String DUREE
		 ,String NIVEAUETUDE, String REFERENCE, String REMUNERATION, String SIRET,
		 String SPECIALITE,String TITRESUJET, String TYPECONTRAT, String CONTACTWEB) {
     super();
     this.ADRESSE = ADRESSE;
     this.CONTACTNAME = CONTACTNAME ;
     this.CONTACTTEL = CONTACTTEL;
     this.DESCRIPTIONSUJET = DESCRIPTIONSUJET;
     this.DUREE = DUREE;
     this.NIVEAUETUDE = NIVEAUETUDE;
     this.REFERENCE = REFERENCE ;
     this.REMUNERATION = REMUNERATION;
     this.SIRET=SIRET;
     this.SPECIALITE = SPECIALITE;
     this.TITRESUJET = TITRESUJET;
     this.TYPECONTRAT = TYPECONTRAT;
     this.CONTACTWEB =CONTACTWEB;
 }

public String getID() {
	return ID;
}

public void setID(String iD) {
	ID = iD;
}

public String getSIRET() {
	return SIRET;
}

public void setSIRET(String sIRET) {
	SIRET = sIRET;
}

public String getTITRESUJET() {
	return TITRESUJET;
}

public void setTITRESUJET(String tITRESUJET) {
	TITRESUJET = tITRESUJET;
}

public String getREFERENCE() {
	return REFERENCE;
}

public void setREFERENCE(String rEFERENCE) {
	REFERENCE = rEFERENCE;
}

public String getDESCRIPTIONSUJET() {
	return DESCRIPTIONSUJET;
}

public void setDESCRIPTIONSUJET(String dESCRIPTIONSUJET) {
	DESCRIPTIONSUJET = dESCRIPTIONSUJET;
}

public String getSPECIALITE() {
	return SPECIALITE;
}

public void setSPECIALITE(String sPECIALITE) {
	SPECIALITE = sPECIALITE;
}

public String getREMUNERATION() {
	return REMUNERATION;
}

public void setREMUNERATION(String rEMUNERATION) {
	REMUNERATION = rEMUNERATION;
}

public String getADRESSE() {
	return ADRESSE;
}

public void setADRESSE(String aDRESSE) {
	ADRESSE = aDRESSE;
}

public String getCONTACTNAME() {
	return CONTACTNAME;
}

public void setCONTACTNAME(String cONTACTNAME) {
	CONTACTNAME = cONTACTNAME;
}

public String getCONTACTTEL() {
	return CONTACTTEL;
}

public void setCONTACTTEL(String cONTACTTEL) {
	CONTACTTEL = cONTACTTEL;
}

public String getCONTACTWEB() {
	return CONTACTWEB;
}

public void setCONTACTWEB(String cONTACTWEB) {
	CONTACTWEB = cONTACTWEB;
}

public String getTYPECONTRAT() {
	return TYPECONTRAT;
}

public void setTYPECONTRAT(String tYPECONTRAT) {
	TYPECONTRAT = tYPECONTRAT;
}

public String getDUREE() {
	return DUREE;
}

public void setDUREE(String dUREE) {
	DUREE = dUREE;
}

public String getNIVEAUETUDE() {
	return NIVEAUETUDE;
}

public void setNIVEAUETUDE(String nIVEAUETUDE) {
	NIVEAUETUDE = nIVEAUETUDE;
}
}

